baseurl = ""
title = "Lorenzo Popescu"

theme = "hugo-coder"

defaultcontentlanguage = "en"
languagecode = "en"

paginate = 20
canonifyurls = true
relativeURLs = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Lorenzo Popescu"
    description = "Personal site"
    keywords = "blog,developer,personal"
    info = "Computer science student"
    avatar=true
    avatarurl = "images/logo.png"
    footercontent = "In development..."


    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2020

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/lorenzoo02"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 2
    url = "https://www.instagram.com/lorenzoo.02"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/Lorenzo30042086"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram"
    weight = 4
    url = "https://telegram.me/lorenzo2202"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook"
    weight = 5
    url = "https://www.facebook.com/lorenzo.popescu.3/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.it]
        languagename = "Italiano"

        [languages.it.params]
            author = "Lorenzo Popescu"
            info = "Studente di informatica"
            description = "Sito personale"
            keywords = "blog,sviluppatore,personale"
            footercontent = "In sviluppo..."

        [languages.it.menu]

            [[languages.it.menu.main]]
            name = "Di"
            weight = 1
            url = "about/"

            [[languages.it.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.it.menu.main]]
            name = "Progetti"
            weight = 3
            url = "projects/"

            [[languages.it.menu.main]]
            name = "Contattami"
            weight = 5
            url = "contact/"
